---
- name: start phpVirtualBox docker container
  docker_container:
    name: phpvirtualbox
    image: joweisberg/phpvirtualbox
    pull: true
    state: started
    env:
      VBOX_HOSTPORT: "{{virtualbox_host}}"
      VBOX_NAME: "{{virtualbox_servername}}"
      VBOX_USER: "{{virtualbox_user}}"
      VBOX_PW: "{{virtualbox_user_password}}"
      CONF_browserRestrictFolders: "/home"
      # This does not work. This string is not properly transformed to a map.
      # CONF_authConfig: "'host'=>'ds.fritz.box','bind_dn'=>'uid=%s,cn=users,dc=stephan-hildebrandt,dc=eu'"
    ports:
      "{{php_virtualbox_port}}:80"
    restart_policy: always

- name: Print note about authentication
  debug:
    msg: Default credentials are 'admin'/'admin'. Please change them via UI.