---
- name: start phpVirtualBox docker container
  docker_container:
    name: phpvirtualbox
    image: joweisberg/phpvirtualbox
    pull: true
    state: started
    env:
      VBOX_HOSTPORT: "{{virtualbox_host}}"
      VBOX_NAME: "{{virtualbox_servername}}"
      VBOX_USER: "{{virtualbox_user}}"
      VBOX_PW: "{{virtualbox_user_password}}"
      CONF_browserRestrictFolders: "/home"
    ports:
      "{{php_virtualbox_port}}:80"
    restart_policy: always