---
- name: Create phpvirtualbox config dir
  file:
    path: "{{php_virtualbox_config_dir}}"
    state: directory
    mode: '0600'

- name: Create phpVirtualBox compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{php_virtualbox_config_dir}}/docker-compose.yml"
    mode: '0600'

- name: Start phpVirtualBox docker container
  docker_compose:
    project_src: "{{php_virtualbox_config_dir}}"
    