---
elasticsearch_version: 7.6.2
elasticsearch_rest_port: 9200
elasticsearch_nodes_port: 9300
elasticsearch_heap_size: 2g
elasticsearch_data_volume_name: elastic_data
elasticsearch_admin_username: elastic
elasticsearch_admin_password: changeme

kibana_version: 7.6.2
kibana_port: 5601
kibana_data_volume_name: kibana_data
kibana_config_dir: /var/kibana/config