---
- name: Basic setup
  hosts: all
  become: true

  tasks:
    - name: Enable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo ALL='
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Set timezone to Berlin
      timezone:
        name: Europe/Berlin

    - name: Avoid memory swapping
      sysctl:
        name: vm.swappiness
        value: "0"

    - name: Send syslogs to {{rsyslog_server}}
      lineinfile:
        path: /etc/rsyslog.conf
        state: present
        regexp: '^\*\.\*'
        line: '*.* @{{rsyslog_server}}'
      notify:
        - restart rsyslog

    - name: Install nfs
      package: 
        name: nfs-common

    - name: Create mount point for NFS share
      file:
        path: '{{nfs.mount_dir}}'
        state: directory
        mode: '1777'


    - name: Mount NFS storage share for this machine
      mount:
        path: '{{nfs.mount_dir}}'
        src: '{{ nfs.base_share }}'
        state: mounted
        fstype: nfs

  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted