---
- name: Basic setup
  hosts: all
  become: true

  tasks:
    - name: Enable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo ALL='
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Set timezone to Berlin
      timezone:
        name: Europe/Berlin

    - name: Avoid memory swapping
      sysctl:
        name: vm.swappiness
        value: "0"

    - name: Send syslogs to {{rsyslog_server}}
      lineinfile:
        path: /etc/rsyslog.conf
        state: present
        regexp: '^\*\.\*'
        line: '*.* @{{rsyslog_server}}'
      notify:
        - restart rsyslog

  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted