---
- name: Setup Cockpit
  hosts: cockpit
  become: true

  tasks:
    - name: Install Cockpit
      package:
        name:
        - cockpit
        - cockpit-pcp

    - name: Create cockpit.conf
      copy:
        dest: /etc/cockpit/cockpit.conf
        content: |
          [WebService]
          AllowUnencrypted = true

          [Session]
          IdleTimeout = 0
      notify: restart cockpit

  handlers:
    - name: restart cockpit
      systemd:
        name: cockpit.socket
        state: restarted
        daemon_reload: true