---
- name: Setup Gitlab Runner
  hosts: gitlab_runner
  become: true

  tasks:
    - name: Add Gitlab repo keys
      apt_key:
        url: "https://packages.gitlab.com/runner/gitlab-runner/gpgkey"
        state: present
        
    - name: Add Gitlab repo
      apt_repository:
        repo: 'deb https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ {{ ansible_distribution_release }} main'
        state: present
        update_cache: yes

    - name: Install Gitlab Runner
      apt:
        name: gitlab-runner
        state: present
      environment:
        GITLAB_RUNNER_DISABLE_SKEL: true