---
- name: Setup Gitlab Runner
  hosts: gitlab_runner
  become: true

  tasks:
    - name: Create gitlab-runner config dir
      file:
        path: "{{gitlab_runner_config_dir}}"
        state: directory
        mode: '0600'

    - name: Create gitlab-runner compose file
      template:
        src: gitlab_runner/docker-compose.yml.j2
        dest: "{{gitlab_runner_config_dir}}/docker-compose.yml"
        mode: '0600'

    - name: Start gitlab-runner docker container
      docker_compose:
        project_src: "{{gitlab_runner_config_dir}}"