---
- name: Setup Gitlab
  hosts: gitlab
  become: true

  tasks:
    - name: create {{gitlab_config_dir}}
      file:
        path: "{{gitlab_config_dir}}"
        state: directory
        mode: '0755'

    - name: Save gitlab config file
      template:
        src: templates/gitlab/gitlab.rb.j2
        dest: "{{gitlab_config_dir}}/gitlab.rb"
        mode: '0644'

    - name: Create docker-compose file
      template:
        src: templates/gitlab/docker-compose.yml.j2
        dest: "{{gitlab_config_dir}}/docker-compose.yml"
        mode: '0600'

    - name: create {{gitlab_data_dir}}
      file:
        path: "{{gitlab_data_dir}}"
        state: directory
        mode: '0644'


    - name: create {{gitlab_logs_dir}}
      file:
        path: "{{gitlab_logs_dir}}"
        state: directory
        mode: '0644'

    - name: Start gitlab
      docker_compose:
        project_src: "{{gitlab_config_dir}}"