---
- name: Set up microk8s
  hosts: k8s
  become: true

  tasks:
  - name: Install microk8s
    snap:
      name: microk8s
      classic: true  

  - name: Add user {{k8s_admin_user}} to group 'microk8s'
    user:
      name: "{{k8s_admin_user}}"
      group: microk8s
      append: true


- name: Set up microk8s controller
  hosts: k8s_controller
  become: true

  tasks:
  - name: Install K8s add-ons
    command: "microk8s.enable {{k8s_addons | join(' ')}}"

  - name: Add command shortcuts to bash_aliases of {{k8s_admin_user}}
    become: "{{k8s_admin_user}}"
    lineinfile:
      path: ~/.bash_aliases
      regexp: "^{{item}}$"
      line: "{{item}}"
      create: true
    with_items: "{{bash_aliases}}"

# TODO Generalize so that bash completion for other commands can be easily added.
  - name: Set up kubectl bash completion
    block:
      - command: /snap/bin/microk8s.kubectl completion bash
        register: bash_completion_output

      - copy:
          content: "{{bash_completion_output.stdout}}"
          dest: /etc/bash_completion.d/kubectl

- name: Set up microk8s workers
  hosts: k8s_worker
  become: true

  tasks:
    - name: Print info
      debug:
        msg: "Call microk8s.add-node on the controller and follow directions to add this node the cluser."