- name: Setup GitLab
  hosts: gitlab
  become: true
  
  tasks:
    - name: create {{item}}
      file:
        path: "{{item}}"
        state: directory
        mode: '0755'
      with_items:
        - "{{gitlab_config_dir}}"
        - "{{gitlab_data_dir}}"
        - "{{gitlab_log_dir}}"


    - name: start gitlab container
      docker_container:
        name: gitlab
        image: gitlab/gitlab-ce:{{gitlab_version}}
        pull: true
        state: started
        ports:
        - "{{gitlab_http_port}}:80"
        - "{{gitlab_https_port}}:443"
        - "{{gitlab_ssh_port}}:22"
        restart_policy: always
        volumes:
        - "{{gitlab_config_dir}}:/etc/gitlab"
        - "{{gitlab_data_dir}}:/var/opt/gitlab"
        - "{{gitlab_log_dir}}:/var/log/gitlab"