---
- name: Setup Docker
  hosts: all
  become: true

  roles:
    - role: geerlingguy.docker
      docker_compose_version: "1.25.5"
      docker_compose_path: /usr/bin/docker-compose

    - role: geerlingguy.pip
      pip_install_packages:
        - docker
      pip_package: python3-pip
      pip_executable: pip3

- name: Setup VirtualBox
  hosts: virtualbox
  become: true
  
  vars_files:
    - vars/credentials.yml

  roles:
    - role: virtualbox
      virtualbox_user: "{{vbox_user}}"
      virtualbox_user_pw: "{{virtualbox_password}}" 
      virtualbox_host: 0.0.0.0
      virtualbox_port: "{{vbox_port}}"

    - role: phpvirtualbox
      virtualbox_host: "{{groups['virtualbox'][0]}}:{{vbox_port}}"
      virtualbox_servername: "{{virtualbox_host}}"
      virtualbox_user: "{{vbox_user}}"
      virtualbox_user_password: "{{virtualbox_password}}"
      php_virtualbox_port: "{{php_vbox_port}}"

- import_playbook: playbook-portainer.yml