---
- name: Update all packages on virtual hosts
  hosts: virtual_hosts
  become: true

  tasks:
    - name: Update all packages
      package:
        name: '*'
        state: latest

    - name: Reboot
      reboot: