---
- name: Setup Docker and service user
  hosts: all
  become: true
  
  roles:
    - role: geerlingguy.docker
      docker_compose_version: "1.25.5"
      docker_compose_path: /usr/bin/docker-compose
      docker_users:
        - "{{ansible_facts.real_user_id}}"

    - role: geerlingguy.pip
      pip_install_packages:
        - docker
      pip_package: python3-pip
      pip_executable: pip3

- name: Setup portainer
  hosts: portainer
  become: true
  
  tasks:
    - name: create {{portainer_data_dir}}
      file:
        path: "{{portainer_data_dir}}"
        state: directory
        mode: '0755'

    - name: start portainer container
      docker_container:
        name: portainer
        image: portainer/portainer:{{portainer_version}}
        state: started
        ports:
        - "{{portainer_port}}:9000"
        restart_policy: always
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - "{{portainer_data_dir}}:/data"