---
- name: Setup portainer
  hosts: portainer
  
  roles:
    - role: geerlingguy.docker
      docker_compose_version: "1.25.5"
      docker_compose_path: /usr/bin/docker-compose
      docker_users:
        - vagrant
      become: true
      
  tasks:
    # - name: create {{portainer_data_dir}}
    #   file:
    #     path: "{{portainer_data_dir}}"
    #     state: directory
    #     mode: '0755'
    #     owner: "{{ansible_facts.effective_user_id}}"
    #     group: "{{ansible_facts.effective_group_id}}"
    #   become: true

    # - name: start portainer container
    #   docker_container:
    #     name: portainer
    #     image: portainer/portainer:{{portainer_version}}
    #     state: started
    #     ports:
    #     - "{{portainer_port}}:9000"
    #     restart_policy: always
    #     volumes:
    #     - /var/run/docker.sock:/var/run/docker.sock
    #     - "{{portainer_data_dir}}:/data"