- name: Setup SonarQube
  hosts: sonarqube
  become: true
  
  vars_files:
    - vars/credentials.yml
    - vars/main.yml

  roles:
    - role: sonarqube-docker
      sonarqube_config_dir: /etc/docker-services/sonarqube
      sonarqube_version: 8.3.1-community
      sonarqube_postgres_version: 12.3
      sonarqube_port: "{{ports.sonarqube}}"


