---
- name: Setup VirtualBox
  hosts: virtualbox
  become: true
  
  vars_files:
    - vars/credentials.yml
    - vars/ports.yml

  vars:
    vbox_user: virtualbox
    vbox_port: 18083

  roles:
    - role: virtualbox
      virtualbox_user: "{{vbox_user}}"
      virtualbox_user_pw: "{{virtualbox_password}}" 
      virtualbox_host: 0.0.0.0
      virtualbox_port: "{{vbox_port}}"

    - role: phpvirtualbox
      virtualbox_host: "{{groups['virtualbox'][0]}}:{{vbox_port}}"
      virtualbox_servername: "{{virtualbox_host}}"
      virtualbox_user: "{{vbox_user}}"
      virtualbox_user_password: "{{virtualbox_password}}"
      php_virtualbox_port: "{{ports_phpvirtualbox}}"