- name: Setup elastic stack
  hosts: elastic
  become: true

  vars_files:
    - vars/credentials.yml
  
  roles:
    - role: elastic
      elasticsearch_version: 7.7.1
      elasticsearch_rest_port: 8083
      elasticsearch_nodes_port: 8084
      kibana_version: 7.7.1
      kibana_port: 8085
      elasticsearch_admin_username: "{{elastic_username}}"
      elasticsearch_admin_password: "{{elastic_password}}"