---
- name: Setup Gitlab
  hosts: gitlab
  become: true
  
  vars_files:
    - vars/credentials.yml
    - vars/main.yml

  roles:
    - role: gitlab-docker
      gitlab_config_dir: "{{docker_services_root}}/gitlab"
      gitlab_version: 13.1.2-ce.0
      gitlab_http_port: "{{ports.gitlab_http}}"
      gitlab_https_port: "{{ports.gitlab_https}}"
      gitlab_ssh_port: "{{ports.gitlab_ssh}}"
      gitlab_ldap_host: "{{ldap.host}}"
      gitlab_ldap_port: "{{ldap.port}}"
      gitlab_ldap_bind_dn: "{{ldap.bind_dn}}"
      gitlab_ldap_bind_dn_password: "{{ldap.bind_dn_password}}"
      gitlab_ldap_base_dn: "{{ldap.base_dn}}"
      gitlab_ldap_username_attribute: "{{ldap.username_attribute}}"
      gitlab_ldap_encryption: "simple_tls"
      gitlab_ldap_verify_certificates: false
      gitlab_smtp_server: "{{smtp.server}}"
      gitlab_smtp_port: "{{smtp.port}}"
      gitlab_smtp_username: "{{smtp.auth_user}}"
      gitlab_smtp_password: "{{smtp.auth_pass}}"
      gitlab_smtp_domain: "{{smtp.rewrite_domain}}"
      gitlab_smtp_sender_address: "{{smtp.sender}}"
      gitlab_external_url: "{{gitlab_url}}"