---
- name: Setup auto-start of VMs
  hosts: virtualbox
  become: true

  vars:
    virtualbox_user: virtualbox
    virtual_machines:
      - dev
      - glrunner1
      - office
      - ttrss

  tasks:
  - name: Create service config file
    template:
      src: ./templates/vm_autostart.service.j2
      dest: "/etc/systemd/system/vm_{{item}}.service"
    loop: "{{virtual_machines}}"

  - name: Enable and start services
    service:
      name: vm_{{item}}
      enabled: yes
      state: started
      daemon_reload: yes
    loop: "{{virtual_machines}}"