- name: Setup portainer
  hosts: portainer
  become: true
  
  vars_files:
    - vars/credentials.yml

  roles:
    - role: portainer-docker
      portainer_version: 1.23.2
      portainer_host: "{{groups['portainer'][0]}}"
      portainer_port: 8081