---
- name: Setup Docker and service user
  hosts: all
  become: true
  
  roles:
    - role: geerlingguy.docker
      docker_compose_version: "1.25.5"
      docker_compose_path: /usr/bin/docker-compose
      docker_users:
        - "{{ansible_facts.real_user_id}}"

    - role: geerlingguy.pip
      pip_install_packages:
        - docker
      pip_package: python3-pip
      pip_executable: pip3

- import_playbook: playbook-portainer.yml
- import_playbook: playbook-nexus.yml