- name: Setup portainer
  hosts: portainer
  become: true
  
  vars_files:
    - vars/credentials.yml
    - vars/main.yml

  roles:
    - role: portainer-docker
      portainer_config_dir: "{{docker_services_root}}/portainer"
      portainer_version: 1.24.0
      portainer_host: "{{groups['portainer'][0]}}"
      portainer_port: "{{ports.portainer}}"
      portainer_ldap_url: "{{ldap.host}}:{{ldap.port}}"
      portainer_ldap_base_dn: "{{ldap.base_dn}}"
      portainer_ldap_bind_dn: "{{ldap.bind_dn}}"
      portainer_ldap_bind_dn_password: "{{ldap.bind_dn_password}}"
      portainer_ldap_username_attribute: "{{ldap.username_attribute}}"