- name: Setup elastic stack
  hosts: elastic
  become: true
  
  roles:
    - role: elastic
      elasticsearch_version: 7.6.2
      elasticsearch_rest_port: 8082
      elasticsearch_nodes_port: 8083
      kibana_version: 7.6.2
      kibana_port: 8084