- name: Setup Prometheus
  hosts: prometheus
  become: true
  
  vars_files:
    - vars/credentials.yml

  roles:
    - role: prometheus-docker
      prometheus_version: v2.18.1
      prometheus_port: 8085
      grafana_port: 8086