- name: Setup elastic stack
  hosts: elastic
  become: true
  
  tasks:
    # https://github.com/elastic/elasticsearch-docker/blob/7c1dc434d32b88b414180cbddc9412acb41cb14c/README.md
    - name: set vm.max_map_count to 262144 in sysctl
      sysctl: name={{ item.key }} value={{ item.value }}
      with_items:
        - { key: "vm.max_map_count", value: "262144" }

    - name: create {{item}}
      file:
        path: "{{item}}"
        state: directory
        mode: '0755'
        # Elastic Search runs with UID 1000:1000.
        owner: "1000"
        group: "1000"
      with_items:
        - "{{elasticsearch_data_dir}}"

    - name: start elasticsearch container
      docker_container:
        name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:{{elasticsearch_version}}
        pull: true
        state: started
        env:
          node.name: elasticsearch
          discovery.type: single-node
          "bootstrap.memory_lock": "true"
          ES_JAVA_OPTS: "-Xms{{elasticsearch_heap_size}} -Xmx{{elasticsearch_heap_size}}"
        ports:
        - "{{elasticsearch_rest_port}}:9200"
        - "{{elasticsearch_nodes_port}}:9300"
        restart_policy: always
        volumes:
          - "{{elasticsearch_data_dir}}:/data"
        ulimits:
          - nofile:65535:65535
          - memlock:-1:-1

