- name: Setup portainer
  hosts: portainer
  become: true
  
  vars_files:
    - vars/credentials.yml

  roles:
    - role: portainer
      portainer_host: "{{groups['portainer'][0]}}"
      portainer_ldap_url: "{{ldap_url}}"
      portainer_ldap_base_dn: "{{ldap_base_dn}}"