---
- import_playbook: base.yml
- import_playbook: docker.yml
- import_playbook: ssmtp.yml
- import_playbook: update.yml
- import_playbook: virtualbox.yml
- import_playbook: portainer.yml
- import_playbook: k8s.yml