---
- import_playbook: base.yml
- import_playbook: docker.yml
- import_playbook: ssmtp.yml
- import_playbook: cockpit.yml
- import_playbook: virtualbox.yml
- import_playbook: microk8s.yml
- import_playbook: update.yml