---
- name: create {{onlyoffice_network_name}} network
  docker_network:
    name: "{{onlyoffice_network_name}}"

- name: create mysql data volume
  docker_volume:
    name: "{{onlyoffice_mysql_data_volume_name}}"

- name: create mysql config dir
  file:
    path: "{{onlyoffice_mysql_config_dir}}"
    state: directory
    mode: '0755'

- name: create mysql config file
  template:
    src: templates/mysql/onlyoffice.cnf.j2
    dest: "{{onlyoffice_mysql_config_dir}}/onlyoffice.cnf"
    mode: 0644

- name: create mysql initdb dir
  file:
    path: "{{onlyoffice_mysql_initdb_dir}}"
    state: directory
    mode: '0755'

- name: create mysql initdb script
  template:
    src: templates/mysql/setup.sql.j2
    dest: "{{onlyoffice_mysql_config_dir}}/setup.sql"
    mode: 0644

- name: start mysql container
  docker_container:
    name: onlyoffice_mysql_server
    image: mysql:{{onlyoffice_mysql_version}}
    pull: true
    state: started
    env:
      MYSQL_ROOT_PASSWORD: "{{onlyoffice_mysql_root_password}}"
      MYSQL_DATABASE: onlyoffice_db
    networks:
      - name: "onlyoffice_network"
    networks_cli_compatible: yes
    restart_policy: always
    volumes:
      - "{{onlyoffice_mysql_data_volume_name}}:/var/lib/mysql"
      - "{{onlyoffice_mysql_config_dir}}:/etc/mysql/conf.d"
      - "{{onlyoffice_mysql_initdb_dir}}:/docker-entrypoint-initdb.d"