---
- name: create portainer data volume
  docker_volume:
    name: "{{portainer_data_volume_name}}"

- name: start portainer container
  docker_container:
    name: portainer
    image: portainer/portainer:{{portainer_version}}
    pull: true
    state: started
    ports:
      - "{{portainer_port}}:9000"
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{portainer_data_volume_name}}:/data" 
    # requires passlib and bcrypt python modules to be installed on the ansible host
    command: "--admin-password='{{ portainer_admin_password | password_hash('bcrypt') }}'"

- name: wait for portainer to start
  wait_for:
    host: "{{portainer_host}}"
    port: "{{portainer_port}}"
    sleep: 10

- name: authenticate as admin user
  uri:
    url: "http://{{portainer_host}}:{{portainer_port}}/api/auth"
    method: POST
    body_format: json
    body: 
      Username: admin
      Password: "{{ portainer_admin_password }}"
    status_code: 200
  register: auth_response

- name: get endpoints
  uri:
    url: "http://{{portainer_host}}:{{portainer_port}}/api/endpoints"
    method: GET
    headers:
      Authorization: "Bearer {{auth_response.json.jwt}}"
  register: endpoints

- name: set up portainer to use local Docker endpoint
  uri:
    url: "http://{{portainer_host}}:{{portainer_port}}/api/endpoints"
    method: POST
    headers:
      Authorization: "Bearer {{auth_response.json.jwt}}"
    body_format: form-urlencoded
    body:
      Name: local
      EndpointType: 1
    status_code: 200
  when: endpoints.json is not defined or (endpoints.json|length == 0)

- name: get settings
  uri:
    url: "http://{{portainer_host}}:{{portainer_port}}/api/settings"
    method: GET
    headers:
      Authorization: "Bearer {{auth_response.json.jwt}}"
  register: settings

- name: update LDAP settings
  uri:
    url: "http://{{portainer_host}}:{{portainer_port}}/api/settings"
    method: PUT
    headers:
      Authorization: "Bearer {{auth_response.json.jwt}}"
    body_format: json
    body:
      AuthenticationMethod: 2
      LDAPSettings:
        AnonymousMode: false
        AutoCreateUsers: true
        ReaderDN: "{{portainer_ldap_reader_dn}}"
        Password: "{{portainer_ldap_password}}"
        URL: "{{portainer_ldap_url}}"
        TLSConfig:
          TLS: true
          TLSSkipVerify: true
        StartTLS: false
        SearchSettings:
          - BaseDN: "{{portainer_ldap_base_dn}}"
            Filter: ""
            UserNameAttribute: "uid"
        GroupSearchSettings: 
          - GroupBaseDN: "{{portainer_ldap_base_dn}}"
            GroupFilter: ""
            GroupAttribute: "member"
  when: "portainer_ldap_base_dn is defined"