---
- name: create portainer data volume
  docker_volume:
    name: "{{portainer_data_volume_name}}"

- name: start portainer container
  docker_container:
    name: portainer
    image: portainer/portainer:{{portainer_version}}
    pull: true
    state: started
    ports:
      - "{{portainer_port}}:9000"
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{portainer_data_volume_name}}:/data" 
    command: --no-auth

- name: wait for portainer to start
  wait_for:
    host: "{{portainer_host}}"
    port: "{{portainer_port}}"
    sleep: 10

- name: get endpoints
  uri:
    url: "http://{{portainer_host}}:{{portainer_port}}/api/endpoints"
    method: GET
  register: endpoints

- name: set up portainer to use local Docker endpoint
  uri:
    url: "http://{{portainer_host}}:{{portainer_port}}/api/endpoints"
    method: POST
    body_format: form-urlencoded
    body:
      Name: local
      EndpointType: 1
    status_code: 200
  when: endpoints.json is not defined or (endpoints.json|length == 0)