---
- name: Install sSMTP
  package:
    name: ssmtp

- name: Create ssmtp.conf
  template:
    src: ../templates/ssmtp.conf.j2
    dest: "/etc/ssmtp/ssmtp.conf"
    mode: '0640'
    owner: root
    group: mail

- name: add mail users to 'mail' group
  user:
    name: "{{item}}"
    group: mail
    append: true
  loop: "{{ssmtp_mail_users}}"