---
- name: Create {{nexus_config_dir}}
  file:
    path: "{{nexus_config_dir}}"
    state: directory
    mode: '0600'

- name: Create docker-compose file
  template:
    src: ../templates/docker-compose.yml.j2
    dest: "{{nexus_config_dir}}/docker-compose.yml"
    mode: '0600'

- name: Start Nexus
  docker_compose:
    project_src: "{{nexus_config_dir}}"