---
- name: create {{docker_services_root}}/metricbeat
  file:
    path: "{{docker_services_root}}/metricbeat"
    state: directory
    mode: '0600'

- name: Save metricbeat config file
  template:
    src: ../templates/metricbeat.yml.j2
    dest: "{{docker_services_root}}/metricbeat/metricbeat.yml"
    mode: '0600'

- name: Create docker-compose file
  template:
    src: ../templates/docker-compose.yml.j2
    dest: "{{docker_services_root}}/metricbeat/docker-compose.yml"
    mode: '0600'

- name: Start metricbeat
  docker_compose:
    project_src: "{{docker_services_root}}/metricbeat"