---
portainer_config_dir: /etc/docker-services/portainer
portainer_host: portainer
portainer_port: 9000
portainer_version: latest
portainer_admin_password: changeme
portainer_ldap_url: ""
portainer_ldap_base_dn: ""
portainer_ldap_bind_dn: ""
portainer_ldap_bind_dn_password: ""
portainer_ldap_username_attribute: "uid"