---
# https://github.com/elastic/elasticsearch-docker/blob/7c1dc434d32b88b414180cbddc9412acb41cb14c/README.md
- name: set vm.max_map_count to 262144 in sysctl
  sysctl: name={{ item.key }} value={{ item.value }}
  with_items:
    - { key: "vm.max_map_count", value: "262144" }

- name: create {{docker_services_root}}/elastic
  file:
    path: "{{docker_services_root}}/elastic"
    state: directory
    mode: '0644'

- name: create {{kibana_config_dir}}
  file:
    path: "{{kibana_config_dir}}"
    state: directory
    mode: '0644'

- name: create elasticsearch config file
  template:
    src: templates/elasticsearch.yml.j2
    dest: "{{docker_services_root}}/elastic/elasticsearch.yml"
    mode: '0644'

- name: create kibana config file
  template:
    src: templates/kibana.yml.j2
    dest: "{{docker_services_root}}/elastic/kibana.yml"
    mode: '0644'

- name: Create docker-compose file
  template:
    src: ../templates/docker-compose.yml.j2
    dest: "{{docker_services_root}}/elastic/docker-compose.yml"
    mode: '0600'
  
- name: Start elastic stack
  docker_compose:
    project_src: "{{docker_services_root}}/elastic"