---
all:
  hosts:
    srv1.fritz.box:
      ansible_user: master
      # There is no python command on this host. Explicitly specify the python interpreter to use.
      ansible_python_interpreter: /usr/bin/python3
    dev.fritz.box:
      ansible_user: master
      ansible_python_interpreter: /usr/bin/python3
    glrunner1.fritz.box:
      ansible_user: master
      ansible_python_interpreter: /usr/bin/python3
    office.fritz.box:
      ansible_user: master
      ansible_python_interpreter: /usr/bin/python3
    ttrss.fritz.box:
      ansible_user: master
      ansible_python_interpreter: /usr/bin/python3
  children:
    physical_hosts:
      hosts:
        srv1.fritz.box:
    virtual_hosts:
      hosts:
        dev.fritz.box:
        glrunner1.fritz.box:
        office.fritz.box:
        ttrss.fritz.box:
    portainer:
      hosts:
        srv1.fritz.box:
    elastic:
      hosts:
        dev.fritz.box:
    gitlab:
      hosts:
        dev.fritz.box:
    gitlab_runner:
      hosts:
        glrunner1.fritz.box:      
    metricbeat:
      hosts:
        srv1.fritz.box:
        dev.fritz.box:
        glrunner1.fritz.box:
        office.fritz.box:
        ttrss.fritz.box:
    ttrss:
      hosts:
        ttrss.fritz.box:
    virtualbox:
      hosts:
        srv1.fritz.box: