---
all:
  hosts:
    srv1.fritz.box:
      ansible_user: administrator
      # There is no python command on this host. Explicitly specify the python interpreter to use.
      ansible_python_interpreter: /usr/bin/python3
  children:
    physical:
      hosts:
        srv1.fritz.box:
    docker:
      hosts:
        srv1.fritz.box: