---
all:
  hosts:
    srv1.fritz.box:
      ansible_user: administrator
      # There is no python command on this host. Explicitly specify the python interpreter to use.
      ansible_python_interpreter: /usr/bin/python3
    gitlab-runner.fritz.box:
      ansible_user: administrator
      ansible_python_interpreter: /usr/bin/python3
    microk8s1.fritz.box:
      ansible_user: administrator
      ansible_python_interpreter: /usr/bin/python3
  children:
    physical:
      hosts:
        srv1.fritz.box:
    cockpit:
      hosts:
        srv1.fritz.box:
        gitlab-runner.fritz.box:
        microk8s1.fritz.box:
    docker:
      children:
        gitlab:
          hosts:
            srv1.fritz.box:
        gitlab_runner:
          hosts:
            gitlab-runner.fritz.box:
    microk8s:
      children:
        microk8s_controller:
          hosts:
            microk8s1.fritz.box:
        microk8s_worker:
          hosts:        
    ssmtp:
      hosts:
        srv1.fritz.box:
    virtualbox:
      hosts:
        srv1.fritz.box:
