---
all:
  hosts:
    srv1:
      ansible_user: master
      # There is no python command on this host. Explicitly specify the python interpreter to use.
      ansible_python_interpreter: /usr/bin/python3
  children:
    elastic:
      hosts:
        srv1:
    metricbeat:
      hosts:
        srv1:
    portainer:
      hosts:
        srv1:
    virtualbox:
      hosts:
        srv1: