---
all:
  hosts:
    srv1.fritz.box:
      ansible_user: master
      # There is no python command on this host. Explicitly specify the python interpreter to use.
      ansible_python_interpreter: /usr/bin/python3
    office.fritz.box:
      ansible_user: master
      ansible_python_interpreter: /usr/bin/python3
  children:
    physical:
      hosts:
        srv1.fritz.box:
    docker:
      children:
        portainer:
          hosts:
            srv1.fritz.box:
    ssmtp:
      hosts:
        srv1.fritz.box:
        office.fritz.box:
    virtualbox:
      hosts:
        srv1.fritz.box: