---
all:
  hosts:
    srv1.fritz.box:
      ansible_user: master
      # There is no python command on this host. Explicitly specify the python interpreter to use.
      ansible_python_interpreter: /usr/bin/python3
    office.fritz.box:
      ansible_user: master
      # There is no python command on this host. Explicitly specify the python interpreter to use.
      ansible_python_interpreter: /usr/bin/python3
    dev.fritz.box:
      ansible_user: master
      # There is no python command on this host. Explicitly specify the python interpreter to use.
      ansible_python_interpreter: /usr/bin/python3
  children:
    portainer:
      hosts:
        dev.fritz.box:
    elastic:
      hosts:
        dev.fritz.box:
    gitlab:
      hosts:
        dev.fritz.box:
    metricbeat:
      hosts:
        srv1.fritz.box:
        office.fritz.box:
        dev.fritz.box:
    ttrss:
      hosts:
        srv1.fritz.box:        
    virtualbox:
      hosts:
        srv1.fritz.box: